INSERT INTO TB_CATEGORY (NAME) VALUES ('Eletronics');
INSERT INTO TB_CATEGORY (NAME) VALUES ('Book');
INSERT INTO TB_CATEGORY (NAME) VALUES ('Food');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Daron', '1994-08-06', 'Daron@yahoo.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Reggie', '1988-06-12', 'Reggie@gmail.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Abram', '1961-05-14', 'Abram@outlook.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Edmund', '1983-07-01', 'Edmund@gmail.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Carmina', '1998-06-10', 'Carmina@yahoo.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Luke', '1976-07-07', 'Luke@yahoo.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Cecile', '1997-08-30', 'Cecile@outlook.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Werner', '1966-06-27', 'Werner@yahoo.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Emiko', '1977-06-23', 'Emiko@gmail.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Jerri', '1959-09-07', 'Jerri@outlook.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Magali', '1965-12-18', 'Magali@outlook.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Fidel', '1976-05-18', 'Fidel@yahoo.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Misty', '2002-05-28', 'Misty@gmail.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Molly', '1980-06-29', 'Molly@outlook.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Katina', '1968-10-15', 'Katina@yahoo.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Randolph', '1983-11-08', 'Randolph@outlook.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Carlos', '1999-12-09', 'Carlos@gmail.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Riley', '2003-08-11', 'Riley@yahoo.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Ilda', '1985-05-05', 'Ilda@gmail.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Johnny', '1987-06-01', 'Johnny@gmail.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Janene', '1961-10-10', 'Janene@outlook.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Hugo', '2004-04-08', 'Hugo@gmail.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Anibal', '2002-03-01', 'Anibal@gmail.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Sergio', '1980-03-11', 'Sergio@yahoo.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Leslie', '1961-08-27', 'Leslie@yahoo.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Hilda', '1975-03-26', 'Hilda@yahoo.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Edwardo', '1985-11-05', 'Edwardo@yahoo.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Daine', '1974-11-29', 'Daine@yahoo.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Clarice', '1998-11-02', 'Clarice@outlook.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Delisa', '1995-01-30', 'Delisa@outlook.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Austin', '1998-11-18', 'Austin@gmail.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Austin', '1975-08-29', 'Austin@outlook.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Damien', '1995-08-08', 'Damien@gmail.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Tomi', '1962-02-21', 'Tomi@gmail.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Rona', '2004-10-15', 'Rona@gmail.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Betty', '1969-01-05', 'Betty@yahoo.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Rosio', '1963-05-04', 'Rosio@gmail.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Rachal', '1966-12-21', 'Rachal@outlook.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Donnell', '1963-10-20', 'Donnell@yahoo.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Monte', '1994-12-30', 'Monte@yahoo.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Lenard', '1971-04-03', 'Lenard@gmail.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Nam', '2003-11-13', 'Nam@gmail.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Effie', '1984-05-18', 'Effie@outlook.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Silas', '1980-03-31', 'Silas@outlook.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Paris', '2003-09-26', 'Paris@outlook.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Beryl', '1958-10-13', 'Beryl@outlook.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Katharyn', '1970-04-02', 'Katharyn@yahoo.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Harvey', '2001-09-13', 'Harvey@yahoo.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Clyde', '1995-08-30', 'Clyde@yahoo.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Vikki', '1962-09-12', 'Vikki@yahoo.com');
INSERT INTO TB_ORDER_STATUS (STATUS) VALUES ('PROCESSING');
INSERT INTO TB_ORDER_STATUS (STATUS) VALUES ('CANCELED');
INSERT INTO TB_ORDER_STATUS (STATUS) VALUES ('APROVED');
