INSERT INTO TB_CATEGORY (NAME) VALUES ('Eletronics');
INSERT INTO TB_CATEGORY (NAME) VALUES ('Book');
INSERT INTO TB_CATEGORY (NAME) VALUES ('Food');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Alease', '1971-06-12', 'Alease@gmail.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Myron', '1969-05-23', 'Myron@gmail.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Kristin', '1997-11-12', 'Kristin@gmail.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Milton', '1998-03-21', 'Milton@yahoo.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Michael', '1979-09-25', 'Michael@outlook.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Kristofer', '1967-06-03', 'Kristofer@yahoo.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Jason', '1993-08-05', 'Jason@yahoo.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Kristle', '1989-02-03', 'Kristle@outlook.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Shyla', '1987-02-02', 'Shyla@gmail.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Greg', '1983-09-19', 'Greg@yahoo.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Matilda', '1972-02-28', 'Matilda@outlook.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Darcey', '1969-08-01', 'Darcey@yahoo.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Terisa', '1976-03-04', 'Terisa@outlook.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Gerry', '1961-04-23', 'Gerry@gmail.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Cristobal', '1964-01-02', 'Cristobal@gmail.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Krystal', '1994-07-28', 'Krystal@yahoo.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Terese', '2001-10-21', 'Terese@outlook.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Connie', '2004-02-16', 'Connie@gmail.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Stacy', '1981-10-03', 'Stacy@outlook.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Santiago', '1990-05-21', 'Santiago@outlook.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Diego', '2000-06-30', 'Diego@outlook.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Britany', '1964-01-27', 'Britany@gmail.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Wilbert', '2004-01-01', 'Wilbert@yahoo.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Reyes', '1991-02-27', 'Reyes@yahoo.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Irwin', '2000-09-21', 'Irwin@outlook.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Mathew', '1960-01-31', 'Mathew@outlook.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Maira', '1997-09-10', 'Maira@gmail.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Rodolfo', '1960-02-11', 'Rodolfo@outlook.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Eusebio', '1978-04-02', 'Eusebio@gmail.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Chantay', '1970-03-06', 'Chantay@outlook.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Lizbeth', '1975-02-22', 'Lizbeth@yahoo.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Jessica', '1976-07-18', 'Jessica@outlook.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Toby', '1974-09-07', 'Toby@gmail.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Rebecca', '1976-09-07', 'Rebecca@outlook.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Alonzo', '1979-02-02', 'Alonzo@outlook.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Garrett', '1968-03-24', 'Garrett@yahoo.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Miquel', '1992-09-05', 'Miquel@outlook.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Nickolas', '1974-08-25', 'Nickolas@gmail.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Berta', '1976-08-12', 'Berta@yahoo.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Aurelio', '1971-08-31', 'Aurelio@outlook.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Lonny', '1993-07-25', 'Lonny@yahoo.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Quintin', '1983-07-12', 'Quintin@outlook.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Sergio', '1997-05-06', 'Sergio@gmail.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Lenny', '1989-02-20', 'Lenny@gmail.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Timothy', '1996-06-24', 'Timothy@yahoo.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Garth', '1969-01-07', 'Garth@outlook.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Christi', '1986-08-22', 'Christi@gmail.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Agustin', '1998-06-02', 'Agustin@gmail.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Leopoldo', '1998-11-19', 'Leopoldo@yahoo.com');
INSERT INTO TB_CLIENT (name, birthday, email) VALUES ('Guadalupe', '2004-02-11', 'Guadalupe@yahoo.com');
INSERT INTO TB_ORDER_STATUS (STATUS) VALUES ('PROCESSING');
INSERT INTO TB_ORDER_STATUS (STATUS) VALUES ('CANCELED');
INSERT INTO TB_ORDER_STATUS (STATUS) VALUES ('APROVED');
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Limes', 2.3, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Fingerlime', 4.89, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Butternut pumpkin', 2.25, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Lemon', 4.63, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Limes', 1.67, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Currants', 3.03, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Lychees', 2.63, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Dragonfruit', 4.29, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Kiwiberries', 4.11, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Guava', 1.27, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Strawberries', 1.88, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Dates', 2.7, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Custard Apples', 1.58, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Nectarines', 4.61, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Fingerlime', 1.83, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Limes', 4.96, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Pomegranate', 4.5, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Custard Apples', 1.04, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Goji Berry', 1.59, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Oranges', 3.35, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Cantaloupe', 2.72, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Melon', 1.47, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Snowpeas', 1.88, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Banana', 1.42, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Prunes', 3.9, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Pomegranate', 4.87, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Limes', 4.44, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Papaya', 4.16, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Sprouts', 2.46, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Jarrahdale pumpkin', 3.9, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Kiwi Fruit', 2.26, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Figs', 1.3, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Peaches', 3.29, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Longan', 1.3, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Blueberries', 4.2, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Oranges', 5.0, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Avocado', 2.99, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Blackberries', 1.77, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Olives', 3.23, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Tomatoes', 3.26, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Watermelon', 4.3, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Cherries', 2.77, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Juniper Berries', 3.85, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Sprouts', 4.78, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Banana', 4.46, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Olives', 2.91, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Aubergine', 3.69, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Mulberries', 3.52, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Passionfruit', 1.24, 3);
INSERT INTO TB_PRODUCT (NAME, PRICE, CATEGORY_ID) VALUES ('Jarrahdale pumpkin', 1.19, 3);
